[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"

[variables]
NODE_OPTIONS = "--max-old-space-size=4096"
NIXPACKS_NODE_VERSION = "20"
