[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "sh -c 'HOSTNAME=0.0.0.0 PORT=${PORT:-8080} exec npm run start'"

[variables]
NODE_OPTIONS = "--max-old-space-size=4096"
NIXPACKS_NODE_VERSION = "20"
